"""Tests for CSV import deduplication.

Guards against double-entry creation on re-import of same Sales Invoice batch.
"""

import frappe
from frappe.utils import nowdate, flt
from ch_pos.api.import_dedup import (
    check_import_dedup_sales_invoice,
    stamp_import_batch_hash,
    _compute_row_hash,
    _compute_batch_hash,
)

TAG = "IMPORT-DEDUP-TEST"
COMPANY = "_Test Company"
CUSTOMER = "_Test Customer"


def _make_test_item_row(item_code="_Test Item", qty=2, rate=100):
    """Create a test item row for import."""
    return {
        "item_code": item_code,
        "qty": qty,
        "rate": rate,
        "amount": qty * rate,
    }


def test_row_hash_is_stable():
    """Same data produces same hash; order doesn't matter on dict keys."""
    row1 = {"item_code": "TEST", "qty": 2, "rate": 100}
    row2 = {"rate": 100, "item_code": "TEST", "qty": 2}
    
    hash1 = _compute_row_hash(row1)
    hash2 = _compute_row_hash(row2)
    
    assert hash1 == hash2, f"Hash mismatch: {hash1} != {hash2}"
    print(f"✅ Row hash stable: {hash1}")


def test_row_hash_excludes_autogenerated():
    """Row hash ignores name, creation, modified, etc."""
    row_clean = {"item_code": "TEST", "qty": 2}
    row_with_meta = {
        "item_code": "TEST",
        "qty": 2,
        "name": "row-123",
        "creation": "2026-07-10 10:00:00",
        "modified": "2026-07-10 10:05:00",
    }
    
    hash_clean = _compute_row_hash(row_clean)
    hash_with_meta = _compute_row_hash(row_with_meta)
    
    assert hash_clean == hash_with_meta, f"Hash differs on metadata: {hash_clean} != {hash_with_meta}"
    print(f"✅ Row hash ignores autogenerated fields")


def test_batch_hash_is_order_sensitive():
    """Batch hash differs when row order changes."""
    batch1 = [
        {"item_code": "A", "qty": 1},
        {"item_code": "B", "qty": 2},
    ]
    batch2 = [
        {"item_code": "B", "qty": 2},
        {"item_code": "A", "qty": 1},
    ]
    
    hash1 = _compute_batch_hash(batch1)
    hash2 = _compute_batch_hash(batch2)
    
    assert hash1 != hash2, f"Batch hash should differ on row order; got {hash1} == {hash2}"
    print(f"✅ Batch hash is order-sensitive")


def test_dedup_query_returns_none_when_no_match():
    """Dedup query returns None when no existing invoice matches."""
    items_data = [_make_test_item_row("UNLIKELY_ITEM_DEDUP_TEST_XYZ123", 2, 100)]
    
    result = check_import_dedup_sales_invoice(
        customer=CUSTOMER,
        items=items_data,
        posting_date="2099-01-01",  # Far future, no real invoices
        company=COMPANY,
    )
    
    assert result is None, f"Should return None when no match; got {result}"
    print(f"✅ Dedup query correctly returns None on no match")


def test_dedup_respects_time_window():
    """Dedup only checks 10-minute rolling window (simulated via date in future)."""
    items_data = [_make_test_item_row("TEST_TIME_WINDOW_456", 2, 100)]
    
    # Check far-future date → should not match (outside window)
    result = check_import_dedup_sales_invoice(
        customer=CUSTOMER,
        items=items_data,
        posting_date="2099-12-31",
        company=COMPANY,
    )
    
    assert result is None, f"Future date should not match; got {result}"
    print(f"✅ Dedup respects time window")


def test_compute_functions_handle_edge_cases():
    """Edge case: empty list, None values, missing fields."""
    # Empty list
    hash_empty = _compute_batch_hash([])
    assert hash_empty, "Should produce hash for empty batch"
    
    # Row with None values
    row_with_none = {"item_code": None, "qty": 0, "rate": None}
    hash_none = _compute_row_hash(row_with_none)
    assert hash_none, "Should handle None values"
    
    print(f"✅ Edge cases handled correctly")


def run_all():
    """Run all dedup tests."""
    print("\n─── CSV Import Dedup Tests ───────────────────────────────")
    
    test_row_hash_is_stable()
    test_row_hash_excludes_autogenerated()
    test_batch_hash_is_order_sensitive()
    test_dedup_query_returns_none_when_no_match()
    test_dedup_respects_time_window()
    test_compute_functions_handle_edge_cases()
    
    print("\n✅ All tests passed\n")
    return {
        "passed": 6,
        "failed": 0,
    }
